title: Andrea Bertieri Ruiz
email: abertierir (at) unal.edu.co
description: Data Quality Engineer & Data Analyst 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abertierir.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#google_analytics: G-6TZW3PRHPG

# Build settings
#markdown: kramdown

theme: jekyll-theme-cayman

#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one


#gems:
 # - jekyll-feed

#exclude:
 # - Gemfile
 # - Gemfile.lock
 # - packrat
